### ISSUE TITLE
Why NoInlineVarDocs?

### ISSUE THREAD

**Issue by AmrIKhudair** [tightenco/tlint#108]
What is the problem with having type hinting for vars, and is there an alternative way to type hint vars?

**Comment by mattstauffer** [comment]
This is purely my preference that I've forced on everyone else at Tighten: I don't like code that purely serves IDEs, and that's what those inline doc blocks do.

**Comment by AmrIKhudair** [comment]
Well while I agree with you at this point, as they make the code bulky and a bit messy. But in the mean time php is not providing a proper way to type hint variables. And it is important for third party packages to have type hinting to help the users to know what is the expected type for the variable without having to read the source code to know/guess. Plus some classes may need to use getters/setters like for example Eloquent models. you may want to type hint attributes to make others aware of what fields are in the corresponding table and what types are them without having to access to or reviewing the database schema.

**Comment by mattstauffer** [comment]
So, in case it's not clear, tlint is *very* opinionated. It's almost guaranteed that there are people who are going to disagree with some of its linters, which is why they can all be disabled one-by-one.

In case it's not clear, it's entirely possible to type hint variables; you just can't use docblocks to document types.

I certainly understand the circumstances that would merit this, and even within Tighten, if we had a project or a package that needed those, I'd say "just disable this Linter for that project." These aren't universal rules; they're our best-and-preferred practices for 90% of the code we write.

**Comment by AmrIKhudair** [comment]
Ok now I get it so about this 

> In case it's not clear, it's entirely possible to type hint variables; you just can't use docblocks to document types.

What is the other way to do it that is allowed by Tighten Lint?

**Comment by mattstauffer** [comment]
```php
public function doThing(Thing $thing)
{
    // This is allowed
}
```
```php
public function doThing(Thing $thing)
{
    /** @var ThingCollection */
    $things = $this->thingRepository->getThingsByThing($thing);
    // This is not allowed ^^
}
```
